config/routes.rb
Altoids::Application.routes.draw do

	root 'sessions#splash'
  
	match '/splash', to: 'sessions#splash', via: 'get'
  	match '/home', to: 'sessions#home', via: 'get'
	match '/events_list', to: 'sessions#events_list', via: 'get'
	match '/tearsheet', :to => 'sessions#tearsheet', via: 'get'
	match '/logout', to: 'sessions#destroy', via: 'get'
	
	post 'zencoder' => 'zencoder#create', :as => 'zencoder' # used to direct the "completed job" notification from zencoder	
	  
	resources :videos
	resources :products
	resources :sessions, only: [:new, :create, :destroy]
	resources :users
	resources :venues
	resources :neighborhoods
	resources :features
	resources :venue_features
	resources :events
	resources :venue_events
	resources :password_resets
	

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :venue
  
  # Activerecord callbacks
  before_save :set_default
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  attr_accessor :updating_password
  before_validation :process_data

  # For security reasons,  \A and \z should be used instead of ^ and $ in regular expressions - see Section 6.6 in http://guides.rubyonrails.org/security.html#sessions
  VALID_NAME_REGEX = /\A+[a-z\s]+\z/i
  VALID_ZIP_CODE_REGEX = /\A+[0-9]+\z/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates(:first_name, presence: true, length: { maximum: 20 }, format: { with: VALID_NAME_REGEX, message: "Use letters only)" })
  validates(:last_name, presence: true, length: { maximum: 20 }, format: { with: VALID_NAME_REGEX, message: "Use letters only)" })
  validates(:email, presence: true, format: { with: VALID_EMAIL_REGEX, message: "Requires proper email format" }, uniqueness: { case_sensitive: false })
#  validates(:zip_code, presence: true, length: { is: 5, message: "Requires 5 digits"}, format: { with: VALID_ZIP_CODE_REGEX, message: "Use digits only" })
  validates(:password, length: {minimum: 4}, :if => :should_validate_password? )
   validates :gender, inclusion: { in: [true, false], message: "Please select Male or Female" }
  
  if :should_validate_password?
	has_secure_password  #Section 6.3.4 - Presence validations for the password and its confirmation are automatically added by has_secure_password
  end
  
  def User.new_remember_token  #new_remember_token is a class method (vs. an instance method) since it doesn't need a user instance.
	SecureRandom.urlsafe_base64  # SecureRandom is an interface that contains the urlsafe_base64 method which generates a random URL-safe base64 string
  end

  def User.encrypt(token) #encrypt is a class method (vs. an instance method) since it doesn't need a user instance.
    Digest::SHA1.hexdigest(token.to_s)
  end

	def send_password_reset
		generate_token(:password_reset_token)
		self.password_reset_sent_at = Time.zone.now
		save!
		UserMailer.password_reset(self).deliver
	end
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
  
  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
	
	def set_default
      self.account_type = "user" unless self.account_type
	  self.active = true unless self.active
    end

	#  http://railscasts.com/episodes/41-conditional-validations	
    def should_validate_password?
	  updating_password || new_record?
    end

	def process_data
	  self.first_name = self.first_name.strip.titleize
  	  self.last_name = self.last_name.strip.titleize
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]  #see listing 9.44 - this method was moved to the session_helper file.
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :destroy]

  before_filter :check_for_mobile, :only => [:new, :edit, :create]
  
  def index
	@users = User.all
  end

  def new
	@user = User.new
  end
  
  def create
    @user = User.new(user_params)
	
    if @user.save
		if current_user.nil?
		  sign_in @user
		  flash[:success] = "Welcome to BarFly!!"
		  redirect_to root_path
		elsif current_user.account_type == "admin"
		  flash[:success] = @user.account_type.capitalize + " account for " + @user.first_name + " was created!"
		  redirect_to users_path
		end
    else
#		@venues = Venue.venues_with_events_only
#		@venues = @venues.order("RANDOM()")
#		@venues = @venues.limit(5)
	  if current_user && current_user.account_type == "admin" # if user has signed in already, then creating a new user must be done by an admin in which case admin should be taken to users/new.html.erb
		flash.now[:error] = "Uh oh... please fix your info"
		render 'new'
	  else  
#		render :template => "sessions/splash" # if user has not logged in and received an error message, then user needs to be taken to splash page with appropriate window displayed
		flash[:error] = "Invalid email/password combination"
		params[:create_user] = true
		render 'sessions/splash' # if user has not logged in and received an error message, then call splash.js.erb to take user back to splash page with slider open to the "sign up" form displayed
	  end
    end
  end

  def edit
	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
	if @user.update_attributes(user_params)
	  flash[:success] = "Profile updated"
	  if current_user.account_type == "admin"
		redirect_to users_path  #takes user to index action in user controller
	  else
		redirect_to root_path
	  end
    else
      render 'edit'
    end
  end	
  
  def destroy
	User.find(params[:id]).destroy
	flash[:success] = "User deleted."
	redirect_to users_url
  end

  
  private  #See Listing 7.22: Private functions are used internally by the controller (and don't need to be exposed to external users via the Web)

    def user_params #See Chapter 7.3.2 for strong parameters.  Params.require ensures that the params hash has a :user attribute, and permits only the name, email, password, and password confirmation attributes (but no others) to be passed to User.new in the create method.	
	  if !current_user.nil? && current_user.account_type == 'admin'
        params.require(:user).permit(:first_name, :last_name, :zip_code, :email, :password, :password_confirmation, :gender, :birthday, :account_type, :venue_id)
	  else
        params.require(:user).permit(:first_name, :last_name, :zip_code, :email, :password, :password_confirmation, :gender, :birthday)
	  end
    end
			
	def correct_user
      user = User.find_by(id: params[:id])
	  if user
		  unless (current_user?(user) || current_user.account_type == 'admin')
			flash[:error] = "Ooops... looks like you aren't authorized to do that. 1"
			redirect_to(root_url) 
		  end
	  else
		flash[:error] = "Ooops... looks like you aren't authorized to do that. 2"
		redirect_to(root_url) 
	  end
    end
	
end

app/views/users/_edit.html.erb
			<%= bootstrap_form_for(@user, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-9") do |f| %>
				<%= f.alert_message "Please fix the errors below:" %>
<% if false %>  Debugging only
				<%= f.error_summary %>
<% end %>			
				
				<%= render 'form', f: f %>
				
				<div class='text-center'> 
					<%= f.submit 'Update', class: 'btn btn-success' %>
				</div>	
			<% end %>

app/views/users/_form.html.erb
	<%= f.text_field :first_name, label: "First Name", placeholder: "Enter First Name" %>
	<%= f.text_field :last_name, label: "Last Name", placeholder: "Enter Last Name"  %>
	<%= f.email_field :email, placeholder: "Enter Email" %>
	<%= f.password_field :password, placeholder: "Create a Password" %>
	<%= f.password_field :password_confirmation, hide_label: true, placeholder: "Re-enter Password" %>
	<%= f.date_select :birthday, start_year: Date.today.year - 21,
                            end_year: Date.today.year - 90, 
							discard_day: false,
                            order: [:month, :day, :year] %>
	<%= f.form_group :gender, label: { text: "Gender" } do %>
		<%= f.radio_button :gender, 1, label: "Male", inline: true, checked: (@user.gender == true if !@user.nil?) %>
		<%= f.radio_button :gender, 0, label: "Female", inline: true, checked: (@user.gender == false if !@user.nil?) %>
	<% end %>
<% if false %>	
	<!--  Remove if statement to seed admin user into postgreSQL db (also need to modify user_params condition in User controller -->
	<% if params[:action] != "home" && !current_user.nil? && current_user.account_type == "admin" %>
		<%= f.select :account_type, ["user","venue","admin"], {:selected => @user.account_type} %>
		<% if @user.venue.nil? %>
			<%= f.select :venue_id, Venue.all.collect{|p| [p.name, p.id]}, { :prompt => "Select Venue" } %>		
		<% else %>
			<%= f.select :venue_id, Venue.all.collect{|p| [p.name, p.id]}, {include_blank: false, :selected => @user.venue.id} %>
		<% end %>	
	<% end %>
<% end %>	
	<% if params[:action] != "home" && !current_user.nil? && current_user.account_type == "admin" %>
		<%= f.form_group :active, label: { text: "Active" } do %>
			<%= f.radio_button :active, 1, label: "True", inline: true, checked: (@user.active == true if !@user.nil?) %>
			<%= f.radio_button :active, 0, label: "False", inline: true, checked: (@user.active == false if !@user.nil?) %>
		<% end %>
	<% end %>

app/views/users/edit.html.erb
<div class="container">

	<div class="panel panel-default">
	
		<!-- Default panel contents -->
		<div class="panel-heading">
			<%= link_to "Cancel", "#", class:"back-button btn btn-xs btn-danger pull-right format-right-margin hidden-xs hidden-sm" %>				
			<h3 class="panel-title"><%= @user.first_name %>'s Profile</h3>
		</div><!-- panel heading  -->

		<div class="panel-body">
			<%= render partial: 'edit' %>
		</div> <!-- panel body -->
		
	</div> <!-- panel -->
	
</div> <!-- container -->

app/views/users/edit.js.erb
var preloader = $("#mainModal .preloader");
var modalBodyContent = $("#mainModal .modal-body-content");

$(modalBodyContent).html("<%= escape_javascript(render partial: 'edit' ) %>");

$(preloader).hide();
$(modalBodyContent).show();

app/views/users/index.html.erb
<div class="container">

	<div class="panel panel-default">
	
		<div class="panel-heading">
			<%= link_to "Add User", new_user_path, class:"btn btn-xs btn-primary pull-right" %>
			<h3 class="panel-title">Users</h3>
		</div>
  
		<div class="table-responsive well">
			<table class="table table-condensed table-hover">
				<thead>
					<tr>
						<th class="visible-lg">ID</th>
						<th>Name</th>
						<th class="hidden-xs">Email</th>
						<th class="hidden-xs">Account Type</th>
						<th class="hidden-xs hidden-sm">Date Joined</th>
						<th class="hidden-xs hidden-sm">Last Activity</th>							
						<th class="visible-lg">Zip Code</th>
						<th class="hidden-xs">Venue Name</th>
						<th></th>
					</tr>
				</thead>
				<tbody> 
					<% for user in @users %>
						<tr>
							<td class="visible-lg"><%= user.id %></td>
							<td><%= link_to user.first_name+" "+user.last_name, edit_user_path(user.id) %></td>
							<td class="hidden-xs"><%= user.email %></td>
							<td class="hidden-xs"><%= user.account_type %></td>
							<td class="hidden-xs hidden-sm"><%= user.created_at.in_time_zone.strftime("%b %e, %Y @%l:%M %p") %></td>
							<td class="hidden-xs hidden-sm">TBD</td>
							<td class="visible-lg"><%= user.zip_code %></td>
							<% if !user.venue.nil? %>
								<td class="hidden-xs">	
									<%= link_to user.venue.name, edit_venue_path(user.venue.id) %>
								</td>
							<% else %>
								<td class="hidden-xs">&nbsp;</td>
							<% end %>
							<% if current_user.account_type == "admin" %>
								<td><%= link_to "Delete", user, method: :delete, data: { confirm: "You sure?" } %></td>
							<% end %>
						</tr>	
					<% end %>
				</tbody>
			</table>
		</div> <!-- table -->
		
	</div> <!-- panel -->
	
</div> <!-- container -->

app/views/users/new.html.erb
<div class="container">

	<div class="panel panel-default">
	
		<!-- Default panel contents -->
		<div class="panel-heading">
			<h3 class="panel-title">Sign up!</h3>
			<%= link_to "Cancel", "#", class:"back-button btn btn-xs btn-danger pull-right hidden-xs hidden-sm" %>				
		</div><!-- panel heading  -->

		<div class="panel-body">
			<%= bootstrap_form_for(@user, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-9") do |f| %>
				<%= f.alert_message "Please fix the errors below:" %>
<% if false %>  Debugging only
			<%= f.error_summary %>
<% end %>			
				
				<%= render 'form', f: f %>
				
				<div class='text-center'>
					<%= f.submit 'Create Account', class: 'btn btn-success' %>
				</div>	
			<% end %>
		</div> <!-- panel body -->
	
	</div> <!-- panel -->
	
</div> <!-- container -->