config/routes.rb
Altoids::Application.routes.draw do

	root 'sessions#splash'
  
	match '/splash', to: 'sessions#splash', via: 'get'
  	match '/home', to: 'sessions#home', via: 'get'
	match '/events_list', to: 'sessions#events_list', via: 'get'
	match '/tearsheet', :to => 'sessions#tearsheet', via: 'get'
	match '/logout', to: 'sessions#destroy', via: 'get'
	
	post 'zencoder' => 'zencoder#create', :as => 'zencoder' # used to direct the "completed job" notification from zencoder	
	  
	resources :videos
	resources :products
	resources :sessions, only: [:new, :create, :destroy]
	resources :users
	resources :venues
	resources :neighborhoods
	resources :features
	resources :venue_features
	resources :events
	resources :venue_events
	resources :password_resets
	

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :signed_in_user  #see listing 9.44
  before_action :venue_user, only: [:index, :create, :edit, :update, :destroy]
  before_action :correct_venue_user, only: [:index, :create, :edit, :update, :destroy]
  
  def index
    @videos = Video.where(venue_id: params[:venue_id])
	
	# Use Amazon AWS SDK methods (.new and .url_for) to get a url to the S3 object (the thumbnail)
	s3 = AWS::S3.new(:access_key_id => ENV['AWS_KEY_ID_READ'], :secret_access_key => ENV['AWS_KEY_VALUE_READ'])
	@bucket = s3.buckets[ENV['AWS_BUCKET']]
	# Code concepts below should be used in views/index.html.erb
#	object = @bucket.objects['uploads/video/attachment/191/uploadify_test.png']
#	@url = object.url_for(:get, { :expires => 1200.minutes.from_now, :secure => true }).to_s	
  end

  def new
  end
  
  def create
# 	Using jquery upload (vs. Carrierwave) to upload videos.  Thus, .fileupload() (assets/javascript/video.js.coffee)
#	has dataType set to "script" which means it is expecting to receive a javascript from the server which
#	in this case comes from the create action in the Videos controller and uses a javascript template (app/views/videos/create.js.erb)
	@video = Video.create(video_params) #creates a new record

#	Web-service support doesn't seem to be necessary: http://api.rubyonrails.org/classes/ActionController/MimeResponds.html#method-i-respond_to	
#	respond_to do |format|
#		format.js # automatically executes:  "render :template => 'videos/create.js.erb'"
#	end

  
#	Code below is for using Carrierwave to upload videos.  
# 	No need to use coerce method because not using Uploadify (doesn't work on iPhones)  
#	newparams = coerce(params)
		#DEBUG: redirect_to resumes_path, notice: "newparams: #{newparams}"
	
#	@video = Video.new(video_params)
#	#DEBUG: redirect_to videos_path, notice: "newparams: #{newparams}"
#		
#    if @video.save
#		redirect_to videos_path, notice: "The video #{@video.name} has been uploaded."
#		#DEBUG: redirect_to videos_path, notice: "cool - params: #{params}"
#    else
#		render "new"
#		#DEBUG:	render :text => "debug: " + params.inspect
#		#DEBUG:	redirect_to videos_path, notice: "crap - params: #{params}"
#    end
  end
  
  def edit
    @video = Video.find(params[:id]) #creates a new record
	
	# Use Amazon AWS SDK methods (.new and .url_for) to get a url to the S3 object (the thumbnail)
	s3 = AWS::S3.new(:access_key_id => ENV['AWS_KEY_ID_READ'], :secret_access_key => ENV['AWS_KEY_VALUE_READ'])
	@bucket = s3.buckets[ENV['AWS_BUCKET']]
	# Code concepts below should be used in views/index.html.erb
#	object = @bucket.objects['uploads/video/attachment/191/uploadify_test.png']
#	@url = object.url_for(:get, { :expires => 1200.minutes.from_now, :secure => true }).to_s
	
#	Web-service support doesn't seem to be necessary: http://api.rubyonrails.org/classes/ActionController/MimeResponds.html#method-i-respond_to		
#	respond_to do |format|
#		format.js # automatically executes:  "render :template => 'videos/edit.js.erb'"
#	end
  end
  
  def update
    @video = Video.find(params[:id])
    s3 = AWS::S3.new(:access_key_id => ENV['AWS_KEY_ID_READ'], :secret_access_key => ENV['AWS_KEY_VALUE_READ'])
	@bucket = s3.buckets[ENV['AWS_BUCKET']]
	
	if @video.update_attributes(video_params)
		respond_to do |format|
			if current_user.account_type == "admin" || current_user.account_type == "venue"
				format.js # automatically executes:  "render :template => 'videos/update.js.erb'"
			else
				redirect_to root_path
			end
		end	
	else
		flash[:alert] = "Video update failed.  Please see errors below."
		render 'index'
	end
  
  end

  
  def show
	@video = Video.find(params[:id])
	
	# Use Amazon AWS SDK methods (.new and .url_for) to get a url to the S3 object (the thumbnail)
	s3 = AWS::S3.new(:access_key_id => ENV['AWS_KEY_ID_READ'], :secret_access_key => ENV['AWS_KEY_VALUE_READ'])
	@bucket = s3.buckets[ENV['AWS_BUCKET']]
	# Code concepts below should be used in views/index.html.erb
#	object = @bucket.objects['uploads/video/attachment/191/uploadify_test.png']
#	@url = object.url_for(:get, { :expires => 1200.minutes.from_now, :secure => true }).to_s
  end
  
  
  def destroy
    @video = Video.find(params[:id])
	@videoID = params[:id] # used in video/destroy.js.erb to delete video row in "videos/_video_html.erb"
	
#	http://stackoverflow.com/questions/10054985/how-to-delete-files-recursively-from-an-s3-bucket
#	To delete the entire S3 folder, the aws request but be in the following form:
#	s3.buckets[ENV['AWS_BUCKET']].objects.with_prefix('uploads/video/attachment/89/').delete_all	
	directory_to_be_deleted = File.dirname(@video.attachment.url) # get the directory of a file (e.g. - https://s3.amazonaws.com/barfly_carrierwave/uploads/video/attachment/89)
	# use URI module to get the path of a url - http://www.ruby-doc.org/stdlib-2.1.3/libdoc/uri/rdoc/URI.html
	# then strips the leading slash by using .slice(1..-1) (i.e. strips leading character)
	directory_to_be_deleted = URI(directory_to_be_deleted).path.to_s.slice(1..-1)
	directory_to_be_deleted = directory_to_be_deleted + '/' # need to append a forward slash at the end (e.g. - uploads/video/attachment/89/
#	logger.debug("directory_to_be_deleted: #{directory_to_be_deleted}")
	s3 = AWS::S3.new(:access_key_id => ENV['AWS_KEY_ID_DELETE'], :secret_access_key => ENV['AWS_KEY_VALUE_DELETE'])
	s3.buckets[ENV['AWS_BUCKET']].objects.with_prefix(directory_to_be_deleted).delete_all # deletes all contents on S3 folder under the video ID - http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/S3/ObjectCollection.html
	
    @video.destroy # destroy the record in the db

#	Web-service support doesn't seem to be necessary: http://api.rubyonrails.org/classes/ActionController/MimeResponds.html#method-i-respond_to	
	respond_to do |format|
		format.html {redirect_to videos_path, notice:  "The video #{@video.name} has been deleted."}
		format.js # automatically executes:  "render :template => 'videos/destroy.js.erb'"
	end
  end

  
  private  #See Listing 7.22: Private functions are used internally by the controller (and don't need to be exposed to external users via the Web)

	def video_params
		params.require(:video).permit(:name, :attachment, :live, :status, :active, :venue_id) 
	end
  
  	def correct_venue_user
		unless (current_user.venue_id == params[:venue_id].to_i) || (current_user.account_type == 'admin')
			flash[:error] = "Ooops... looks like you aren't authorized to access that venue."
			redirect_to root_url
		end	
    end
	
	#   See the following about the coerce(param) method - http://martinjhawkins.wordpress.com/2013/10/07/uploadify-with-paperclip-on-rails-tutorial/	
	#  	Uploadify doesn't put the params (:name and :attachment) in the correct params hash structure
	#  	In order to pass strong parameters enforcement, :name and :attachment need to be nested hashes within the :resume key:
	#  		{ 
	#			:resume => {
	#				:name = <insert name>, 
	#				:attachment = <insert attachment>
	#			} 
	#		}
	#  	Instead, uploadify produces the following params hash:
	#  		{
	#			"Filename"=>"old_town_pub.mp4", 
	#			"authenticity_token"=>"dT2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX9BKk=", 
	#			"_CarrierWave_session"=>"dXhXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx03a77bffb", 
	#			"Filedata"=>#<ActionDispatch::Http::UploadedFile:0x2ccf8e0 @tempfile=#<File:C:/Users/MICHAE~1/AppData/Local/Temp/RackMultipart20140904-2140-15cy0hb>, @original_filename="old_town_pub.mp4", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"Filedata\"; filename=\"old_town_pub.mp4\"\r\nContent-Type: application/octet-stream\r\n">, 
	#			"Upload"=>"Submit Query"
	#		}
	# 	No need to use coerce method because not using Uploadify (doesn't work on iPhones)  
#	def coerce(params)
#		if params[:video].nil?
#			params[:video] = Hash.new
#			
#			# set file name
#			if params[:name].nil?
#				params[:video][:name] = DateTime.now.strftime("%b %e, %Y @%l:%M %p")
#			else
#				params[:video][:name] = params[:name]
#				params[:name].delete
#			end 
#			
#			# nest attachment
#			params[:video][:attachment] = params[:attachment]
#	  
#			# use setContentType to determine the MIME format (so not always set to 'application/octet-stream')
#			params[:video][:attachment].content_type = setContentType(params[:attachment].original_filename)
#			# DEBUG: render :text => "debug: " + params[:attachment].original_filename.inspect	  # "american_junkie.mp4"
#			params.delete(:attachment)  # remove the extra :attachment parameter from the params hash
#
#			params[:video]
#		else
#			params
#		end
#	end

#	No need for setContentType because not using Uploadify (doesn't work on iPhone)	
#	def setContentType(originalFileName)
#	
#		fileExtension = originalFileName.split('.').last.downcase # take the last (2nd) element of the newly created array, split by the period - this should be the file extension (i.e. mp4, MOV, etc.)
#		
#		case fileExtension
#			when "mp4"
#				return "video/mp4"
#			when "mov"
#				return "video/quicktime"
#		end
#		
#	end
	
end

app/views/videos/_edit_template.html.erb
<div class="row">
	<div class="col-xs-6 vee-red">
		<div class="row">
			<div class="col-xs-12">
				<%= image_tag(@bucket.objects[@video.get_path("png", "small")].url_for(:get, { :expires => 20.minutes.from_now, :secure => true }).to_s) %>
			</div>	
		</div>	
		<div class="row">
			<div class="col-xs-12">		
				<%= @video.created_at.strftime("%b %e, %Y %l:%M %p") %>
			</div>	
		</div>
	</div>
	<div class="col-xs-6 vee-red">
		<%= bootstrap_form_for(@video, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-9", html: {:id => "video-update-form"}) do |f| %>
			<input type="hidden" name="_method" value="patch">
			<%= f.text_field :name, label: "Name", placeholder: "Enter Video Name" %>
			<%= f.form_group :active, label: { text: "Active" } do %>
				<%= f.radio_button :active, 1, label: "True", inline: true, checked: (@video.active == true) %>
				<%= f.radio_button :active, 0, label: "False", inline: true, checked: (@video.active == false) %>
			<% end %>
		<% end %>	
	</div>
</div>

app/views/videos/_video.html.erb
<!-- 
	partial file for listing for a specific venue (i.e. views_mobile/videos/index.html.erb)
-->

<!-- Need to wrap contents of <td> in <div> tags in order for .slideUp() to function properly: http://stackoverflow.com/questions/467336/jquery-how-to-use-slidedown-or-show-function-on-a-table-row -->
        <td>
			<div class="video_<%= video.id %>">
			<!--
				When using the S3 object method, url_for, the resulting url will follow the following format (i.e. domain-style):
				
					https://barfly-development.s3.amazonaws.com/uploads/video/attachment/204/old_town_pub.mp4
					
				Need to set the option, :force_path_style, to true when using url_for:
				
					https://s3.amazonaws.com/barfly-development/uploads/video/attachment/204/old_town_pub.mp4
					
				For more info on url_for, see http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/S3/S3Object.html#url_for-instance_method	
				For more info on :force_path_style, see http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/S3/S3Object.html
			-->
				<%= image_tag(@bucket.objects[video.get_path("png", "small")].url_for(:get, { :expires => 20.minutes.from_now, :secure => true, :force_path_style => true }).to_s) %>
			</div>	
		</td>
		<td>
			<div class="video_<%= video.id %>">
				<%= video.name %>
			</div>	
		</td>
		<td>
			<div class="video_<%= video.id %>">
				<% if video.active %>
				Active
				<% else %>
				Inactive
				<% end %>
			</div>	
		</td>
		<td>
			<div class="video_<%= video.id %>">
				<!-- :outputs is the key to an hash of an array.  Need to specify which element of the array to retrieve :duration_in_ms. -->
				<%= video.response[:outputs][0][:duration_in_ms]/1000 %> seconds
			</div>	
		</td>
		<td>
			<div class="video_<%= video.id %>">
				<%= video.created_at.strftime("%b %e, %Y %l:%M %p") %>
			</div>	
		</td>
        <td>
			<% if false %>
				URL: <%= @bucket.objects[get_path(video.attachment.url, "MOV")].url_for(:get, { :expires => 20.minutes.from_now, :secure => true }).to_s %>
				URL: <%= @bucket.objects[get_path(video.attachment.url, "mp4")].url_for(:get, { :expires => 20.minutes.from_now, :secure => true }).to_s %>
				URL: <%= @bucket.objects[get_path(video.attachment.url, "MOV")].url_for(:get, { :expires => 20.minutes.from_now, :secure => true }).to_s %>
			<% end %>	

			<div class="video_<%= video.id %>">
				<!-- data attribute in html is "modal_title" but the underscore is turned into a dash, generating "modal-title" for use in jquery -->
				<%= link_to video_path(video.id), class: "btn btn-primary button_video_show", data: { modal_title: video.name } do %>
					<span class="glyphicon glyphicon-eye-open"></span>
					<span>Watch</span>
				<% end %>
				
				<%= link_to edit_video_path(:id => video.id), class: "btn btn-success button_video_edit" do %>
					<span class="glyphicon glyphicon-pencil"></span>
					<span>Edit&nbsp;&nbsp;&nbsp;</span>
				<% end %>
				
	<% if false %>
				<!-- method: :delete option in link_to helper subverts the jquery delegated event for: $(document).on('click', '.video_delete_button', function(event){ event.preventDefault(); });
				<%= link_to video_path(:id => video.id), class: "btn btn-danger button_video_delete", data: { video: video.name }, method: :delete do %>
					<span class="glyphicon glyphicon-trash"></span>
					<span>Delete</span>
				<% end %>
	<% end %>
		
				<%= link_to video_path(:id => video.id), class: "btn btn-danger button_video_delete", data: { video: video.name } do %>
					<span class="glyphicon glyphicon-trash"></span>
					<span>Delete</span>
				<% end %>
			</div>	
		</td>

app/views/videos/_video_template.html.erb
<!-- For HTML5 Video tag info, see http://www.htmlgoodies.com/html5/client/how-to-embed-video-using-html5.html#fbid=y2nyMm_BHEv -->
				<%= tag("video", {controls: false, autoplay: false, loop: true, muted: false, autobuffer: true}, open: true) %>
					<!-- Compatible with: Chrome(desktop), Firefox(desktop) -->
					<% if (params[:action] == 'splash' || params[:action] == 'show') %>
						<%= tag("source", src: @bucket.objects[video.get_path("mp4", "large")].url_for(:get, { :expires => 20.minutes.from_now, :secure => true, :secure => true, :force_path_style => true }).to_s ) %>
					<% else %>
						<%= tag("source", src: @bucket.objects[video.get_path("mp4", "small")].url_for(:get, { :expires => 20.minutes.from_now, :secure => true, :secure => true, :force_path_style => true }).to_s ) %>
					<% end %>
<% if false %>					
					<%= tag("source", src: @bucket.objects[get_path(video.attachment.url, "webm")].url_for(:get, { :expires => 20.minutes.from_now, :secure => true, :secure => true, :force_path_style => true }).to_s ) %>
					<%= tag("source", src: @bucket.objects[get_path(video.attachment.url, "ogv")].url_for(:get, { :expires => 20.minutes.from_now, :secure => true, :secure => true, :force_path_style => true }).to_s ) %>
<% end %>					
<% if false %>
					<source src='https://s3.amazonaws.com/barfly_full_videos/benchmark.mp4' type='video/mp4' /> <!-- AVC(H.264) format -->			
					<source src="https://s3.amazonaws.com/barfly_full_videos/american_junkie.mp4" type="video/mp4" /> <!-- AVC(H.264) format -->
					<source src="https://s3.amazonaws.com/barfly_full_videos/old_town_pub.mp4" type="video/mp4" /> <!-- AVC(H.264) format -->
<% end %>					
					Your browser does not support the video tag.
				<%= tag("/video", {}, open: true) %>
	

app/views/videos/create.js.erb
// Need to keep this file since the controller is calling it.  But, don't need to do anything here.
// One option is to put in code from altoids.js that has to do with creation which would lighten the js file but the benefit is minimal.

<% if @video.new_record? %>
	alert("Failed to upload video: <%= j @video.errors.full_messages.join(', ').html_safe %>");
<% else %>
// 	alert("Success!");
<% end %>

app/views/videos/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/videos/destroy.js.erb
var video_selector = "#video_" + "<%= escape_javascript(@videoID.to_s) %>" // create jquery selector for the video row that has been deleted
$(video_selector).remove();

app/views/videos/edit.js.erb
$('#mainModal').showModal({
	title: "Notification",
	body: "<%= escape_javascript(render partial: 'edit_template') %>",
	defaultBtn: "Cancel",
	primaryBtn: "Save",
	callback: function(){
		$("#btn-primary").off('click');
		$("#btn-primary").on('click', function(){
			$("#mainModal .preloader").css("display", "block"); // call preloader

			var url = $("#video-update-form").attr('action'); // form action contains parameters specifying video id, etc.
			var form_data = $("#video-update-form").serialize(); // Create a series of key/value pairs from data elements in the form
//			var videoID = url.replace("/videos/", "");
//			var video_selector = "#video_" + videoID;
				
			$.post(	url,
				form_data, // need to pass serialized form data since this is a Post request (vs. in a Get request, data is passed in the url).
				function(){
				},
				"script"
			);

		});
	}
});				

app/views/videos/index.html.erb
<div class="container">
	<div class="panel panel-default">
	
		<!-- Default panel contents -->
		<div class="panel-heading">
			<%= link_to "Add Venue", new_venue_path, class:"btn btn-xs btn-primary pull-right" %>
			<h3 class="panel-title format-inline">Videos</h3>
		</div>

		<div class="table-responsive well">

			<table id="video_table" class="table table-condensed table-hover">		
				<thead>
					<tr>
						<th>Video</th>
						<th>Name</th>
						<th>Status</th>
						<th>Duration</th>
						<th>Date</th>
						<th>&nbsp;</th>
					</tr>
				</thead>
				<tbody>

					<% @videos.each do |video| %>
						<!-- provides an anchor for videos/update.js.erb -->
						<% if !video.response.nil? && video.response[:job][:state] == 'finished' %>
							<tr id="video_<%= video.id %>" class="video_<%= video.id %>">
								<%= render partial: 'video', locals: { video: video } %>
							</tr>
						<% end %>
					<% end %>

				</tbody>
			</table>
			
		</div> <!-- table -->

		<!-- Anchor for progress bar -->
		<div class="row">
			<div id="progress-bar-anchor" class="col-sm-offset-2 col-sm-8">
			</div>
		</div>
		<div id="preloader" class="row collapse">
			<div class="col-sm-12">
				<%= image_tag("preloader.GIF", class:"image-center margin-10") %>
			</div>
			<div class="col-sm-12">
				<p class="text-center" >Please wait...<p>
			</div>
		</div>
		
		<!-- Progress bar template -->
		<script id="template-upload" type="text/x-tmpl">
			<div class="upload">
				<% if false %>
					{%=o.name%} // shows the name of the file
				<% end %>
				<div class="progress">
					<div class="progress-bar" role="progressbar" data-transitiongoal="100" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
					</div>
				</div>
			</div>
		</script>


		<div class="panel-body">
			<div class='text-center'> 
				
				<!-- form below uses jquery file upload (vs. carrierwave) to upload videos -->
				<!-- Need to set multipart to true if doing a file upload -->
				<!-- form has class="new_video", id="new_video", action="/videos", method="post" -->
				<!-- action: "/videos" + method: "post" = controller: videos + action: create -->
				<%= form_for Video.new, html: { multipart: true } do |f| %>
					<span class="btn btn-success fileinput-button">
						<span class="glyphicon glyphicon-plus"></span>
						<span>Add files...</span>
						<% if current_user.account_type == "admin" %>
							<%= f.hidden_field :venue_id, value: params[:venue_id] %>
						<% elsif current_user.account_type == "venue" %>
							<%= f.hidden_field :venue_id, value: current_user.venue_id %>
						<% end %>
						<%= f.file_field :attachment, multiple: true, name: "video[attachment]" %>
					</span>
				<% end %>
				
			</div>
		</div>
		
	</div> <!-- panel -->
</div> <!-- container -->

app/views/videos/show.js.erb
var preloader = $("#mainModal .preloader");
var modalBodyContent = $("#mainModal .modal-body-content");

$(modalBodyContent).html("<%= escape_javascript(render partial: 'video_template', object: @video, as: 'video' ) %>");

var video = $(modalBodyContent).find('video').get(0);
	
video.oncanplay = function(){
	$('#mainModal').on('hide.bs.modal', function (e) {
		video.pause();
	})
	preloader.hide();
	modalBodyContent.fadeIn(500);
	video.play();
}

app/views/videos/update.js.erb
$("#mainModal .preloader").css("display", "none"); // hide preloader
$("#mainModal").modal("hide"); // hide modal

var video_selector = "#video_" + "<%= escape_javascript(@video.id.to_s) %>" // create jquery selector for the video row that has been updated

// fade out the original row, update the html, fade in the new row, then rebind buttons (watch, edit, delete) to the updated DOM
$(video_selector).animate({
	opacity: 0
	}, 500, function(){
		$(this).html("<%= escape_javascript(render partial: 'video', object: @video, as: 'video' || "There are no venues at the moment") %>");
		$(video_selector).animate({		
			opacity: 1
		}, 500, function(){
			initModals(); // rebind buttons
		});
	}
);