config/routes.rb
Altoids::Application.routes.draw do

	root 'sessions#splash'
  
	match '/splash', to: 'sessions#splash', via: 'get'
  	match '/home', to: 'sessions#home', via: 'get'
	match '/events_list', to: 'sessions#events_list', via: 'get'
	match '/tearsheet', :to => 'sessions#tearsheet', via: 'get'
	match '/logout', to: 'sessions#destroy', via: 'get'
	
	post 'zencoder' => 'zencoder#create', :as => 'zencoder' # used to direct the "completed job" notification from zencoder	
	  
	resources :videos
	resources :products
	resources :sessions, only: [:new, :create, :destroy]
	resources :users
	resources :venues
	resources :neighborhoods
	resources :features
	resources :venue_features
	resources :events
	resources :venue_events
	resources :password_resets
	

end

app/models/venue.rb
# encoding: utf-8
# Need the commented code above because for some reason, the constant, VALID_DOMAIN_REGEX, causes the following error:
# invalid multibyte char (US-ASCII)
# http://stackoverflow.com/questions/1739836/invalid-multibyte-char-us-ascii-with-rails-and-ruby-1-9

class Venue < ActiveRecord::Base
  has_many :users
  has_many :venue_events, dependent: :destroy
  has_many :events, :through => :venue_events
  belongs_to :neighborhood
  has_many :venue_features, dependent: :destroy
  has_many :features, :through => :venue_features
  has_many :videos, dependent: :destroy
  accepts_nested_attributes_for :videos, allow_destroy: true # http://railscasts.com/episodes/196-nested-model-form-part-1

#  scope VenueEvent.upcoming_event
	
  # Activerecord callbacks
  before_validation :process_data
  geocoded_by :geocoded_address  # Geocoding: http://railscasts.com/episodes/273-geocoder
  after_validation :geocode, :if => :address_changed?
  after_validation :sanitize_domain
  after_find :format_phone_number
    
  # May need to consider regex for UTF-8 characters at some point: http://stackoverflow.com/questions/4717717/invalid-multibyte-char-us-ascii-validating-a-new-user-with-regex-using-ruby
  VALID_NAME_REGEX = /\A+[\w\s\&\,\:\-\']+\z/i
  VALID_ADDRESS_REGEX = /\A+[0-9]+[a-z0-9\s\#\.\-\:\,]+\z/i
  VALID_CITY_REGEX = /\A+[a-z\s\-\.]+\z/i
  VALID_ZIP_CODE_REGEX = /\A+[0-9]+\z/
  VALID_PHONE_REGEX = /\A+[0-9]+\z/
  VALID_DOMAIN_REGEX = 	/\A+([a-z0-9])(([a-z0-9-]{1,61})?[a-z0-9]{1})?(\.[a-z0-9](([a-z0-9-]{1,61})?[a-z0-9‌​]{1})?)?(\.[a-zA-Z]{2,4})+\z/i
  
  validates(:name, presence: true, length: { maximum: 30 }, format: { with: VALID_NAME_REGEX })
  validates(:address, presence: true, length: { maximum: 50 }, format: { with: VALID_ADDRESS_REGEX })
  validates(:city, presence: true, format: { with: VALID_CITY_REGEX })
  validates(:state, presence: true)
  validates(:zip_code, presence: true, length: { is: 5 }, format: { with: VALID_ZIP_CODE_REGEX })
  validates(:phone, presence: true, length: { is: 10 }, format: { with: VALID_PHONE_REGEX })
  validates(:neighborhood_id, presence: true)
  validates(:website, presence: true, format: {with: VALID_DOMAIN_REGEX, message: "Must be in the format www.venuewebsite.com" })
# validates :active, inclusion: { in: [true, false], message: "Please select True or False" }

  validates(:venue_open_mon, presence: true)
  validates(:venue_close_mon, presence: true)
  validates(:venue_open_tue, presence: true)
  validates(:venue_close_tue, presence: true)
  validates(:venue_open_wed, presence: true)
  validates(:venue_close_wed, presence: true)
  validates(:venue_open_thu, presence: true)
  validates(:venue_close_thu, presence: true)
  validates(:venue_open_fri, presence: true)
  validates(:venue_close_fri, presence: true)
  validates(:venue_open_sat, presence: true)
  validates(:venue_close_sat, presence: true)
  validates(:venue_open_sun, presence: true)
  validates(:venue_close_sun, presence: true)

	def get_video(venue_id)
		video = Video.where(venue_id: venue_id).where(status: 'finished').order("RANDOM()").first
		return video
	end

	def count_videos(status)
		# valid status states are: processing, failed, and finished
		counter = 0
		if (status == "processing")
			self.videos.each do |video|
				if video.response.nil?
					counter = counter + 1
				end
			end
		else
			self.videos.each do |video|
				if !video.response.nil? && (video.response[:job][:state] == status)
					counter = counter + 1
				end	
			end
		end
		return counter
	end
	
  def self.get_venues # Returns all venues including event info and neighborhood info.
	
	# http://stackoverflow.com/questions/9795660/postgresql-distinct-on-without-ordering
	# http://stackoverflow.com/questions/5483407/subqueries-in-activerecord

		# SELECT DISTINCT venues.name AS venue_name, venues.id, venues.phone, venues.file_name, 
		# 	neighborhoods.name AS neighborhood_name, neighborhoods.id AS neighborhood_id
		# 	subquery2.name AS venue_event_name, subquery2.description AS venue_event_description, subquery2.start_time AS event_start_time 
		# FROM "venues" 
		# INNER JOIN "neighborhoods" ON "neighborhoods"."id" = "venues"."neighborhood_id" 
		# INNER JOIN "videos" ON "videos"."venue_id" = "venues"."id" 
		# LEFT OUTER JOIN (
		# 	SELECT venue_events.venue_id, venue_events.name, venue_events.description, venue_events.start_time 
		# 	FROM "venue_events" JOIN (
		# 		SELECT MIN(start_time) as event_start_time, end_time as event_end_time, venue_id 
		# 		FROM "venue_events" 
		# 		WHERE (end_time > Datetime('now')) 
		# 		GROUP BY venue_id) subquery1 
		# 	ON subquery1.event_start_time = venue_events.start_time AND subquery1.venue_id = venue_events.venue_id) subquery2 
		# ON subquery2.venue_id = venues.id WHERE (videos.status = 'finished') LIMIT 2 OFFSET 0
	
		subquery1 = VenueEvent.select("MIN(start_time) as event_start_time, venue_id")
		
		# Modified sort_parameter_list to feed into PostGreSQL db used in Heroku
		if (ActiveRecord::Base.connection.adapter_name == 'SQLite') # For a sqlite db
			subquery1 = subquery1.where("end_time > Datetime('now')")
		else
			subquery1 = subquery1.where("end_time > now()")
		end		
		
		subquery1 = subquery1.group("venue_id")
		subquery1 = subquery1.to_sql
		subquery2 = VenueEvent.joins("JOIN (#{subquery1}) subquery1 ON subquery1.event_start_time = venue_events.start_time AND subquery1.venue_id = venue_events.venue_id")
		subquery2 = subquery2.select("venue_events.venue_id, venue_events.name, venue_events.description, venue_events.start_time")
		subquery2 = subquery2.to_sql
		@venues = Venue.joins("LEFT OUTER JOIN (#{subquery2}) subquery2 ON subquery2.venue_id = venues.id")
				
		@venues = @venues.select("venues.name AS venue_name, venues.id, venues.phone, venues.file_name, neighborhoods.name AS neighborhood_name, neighborhoods.id AS neighborhood_id, subquery2.name AS venue_event_name, subquery2.description AS venue_event_description, subquery2.start_time AS event_start_time")
		@venues = @venues.joins(:neighborhood)
  end
  
  
  def self.filter_features(features)
  
  	# JOIN (
	#	 SELECT venue_features.venue_id
	#	 FROM "venue_features" JOIN (
	#		  SELECT features.id as features_id, features.name as features_name
	#		  FROM features
	#		  WHERE features.name = 'Billiards' OR features.name = 'Outdoor Seating \ Patio') subquery3
	#	 ON subquery3.features_id = venue_features.feature_id
	#	 GROUP BY venue_features.venue_id) subquery4
	# ON subquery4.venue_id = venues.id
																								 
		subquery3 = Feature.select("features.id as features_id, features.name as features_name")
		subquery3 = subquery3.where(name: features) # replaced .where("features.name = ?", features)
		subquery3 = subquery3.to_sql
		subquery4 = VenueFeature.joins("JOIN (#{subquery3}) subquery3 ON subquery3.features_id = venue_features.feature_id").group("venue_features.venue_id")
		subquery4 = subquery4.select("venue_features.venue_id")
		subquery4 = subquery4.to_sql
		@venues = @venues.joins("JOIN (#{subquery4}) subquery4 ON subquery4.venue_id = venues.id")  
  end
  
  
  def self.find_events(options={}) # only returns venues that have events
	# http://stackoverflow.com/questions/9795660/postgresql-distinct-on-without-ordering
	# http://stackoverflow.com/questions/5483407/subqueries-in-activerecord
	
#	if (options[:venue_id])
#		select("venues.*, videos.*, videos.id as video_id")
#			.where(id: options[:venue_id])
#			.joins(:videos)
#	else
#		select("venues.*, videos.*, videos.id as video_id")
#			.joins(:videos)
#			.where(id: Video.select("DISTINCT videos.id"))
#			.joins(:venue_events)
#			.where("venue_events.start_time >= ?", Time.now)
#			.order("RANDOM()")
#			.limit(3)
#	end

#SELECT venues.name AS venue_name, venues.phone, venues.file_name, venues.neighborhood_id, 
#	neighborhoods.name AS neighborhood_name, neighborhoods.id, 
#	events.name AS event_type_name, 
#	subquery2.name AS venue_event_name, subquery2.event_id, subquery2.description AS venue_event_description, subquery2.start_time AS event_start_time 
#FROM "venues" 
#INNER JOIN "neighborhoods" ON "neighborhoods"."id" = "venues"."neighborhood_id" 
#LEFT OUTER JOIN 
#	(SELECT venue_events.venue_id, venue_events.event_id AS event_id, venue_events.name, venue_events.description, venue_events.start_time 
#	FROM "venue_events" 
#	JOIN 
#		(SELECT MIN(start_time) as event_start_time, venue_id 
#		FROM "venue_events" 
#		GROUP BY venue_id) subquery1 
#	ON subquery1.event_start_time = venue_events.start_time AND subquery1.venue_id = venue_events.venue_id) subquery2 
#ON subquery2.venue_id = venues.id
#INNER JOIN "events" ON "events"."id" = subquery2.event_id
			
		subquery1 = VenueEvent.select("MIN(start_time) as event_start_time, venue_id").group("venue_id").to_sql
		subquery2 = VenueEvent.joins("JOIN (#{subquery1}) subquery1 ON subquery1.event_start_time = venue_events.start_time AND subquery1.venue_id = venue_events.venue_id")
		subquery2 = subquery2.select("venue_events.venue_id, venue_events.event_id, venue_events.name, venue_events.description, venue_events.start_time").to_sql
		@venues = Venue.joins("LEFT OUTER JOIN (#{subquery2}) subquery2 ON subquery2.venue_id = venues.id")
		@venues = @venues.where(id: [1, 2, 4]) # Just for development purposes - remove for production
		@venues = @venues.select("venues.name AS venue_name, venues.phone, venues.file_name, venues.neighborhood_id, 
			neighborhoods.name AS neighborhood_name, neighborhoods.id, 
			events.name AS event_type_name,
			subquery2.name AS venue_event_name, subquery2.description AS venue_event_description, subquery2.start_time AS event_start_time")
		@venues = @venues.joins(:neighborhood)
		@venues = @venues.joins("INNER JOIN events ON events.id = subquery2.event_id")
			
  end
  
  #  Select venues with live video to showcase on home page
  def self.video_prep(options={})
  
	defaults = {
		:random => false,
		:limit => false
	}
	
	options = defaults.merge(options)

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
#  before_action :signed_in_user  #see listing 9.44
#  before_action :venue_user, only: [:show, :edit, :update]
#  before_action :correct_venue_user, only: [:show, :edit, :update]
#  before_action :admin_user, only: [:new, :edit, :create, :index, :destroy]

#  before_filter :check_for_mobile, :only => [:index, :edit]
 
  def index
	@venues = Venue.all
#	@venues = Venue.joins(:neighborhood)		
#	@venue_event_months = @venue_events.group_by { |month| month.start_time.strftime("%B") }
  end
  
  def show
	@venue = Venue.find(params[:id])
	@days_of_week = Date::ABBR_DAYNAMES	
  end
  
  def new
	@venue = Venue.new
	@days_of_week = [:monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday]
#	@sql_var = @venue.feature_types.to_sql
  end
  
  def create
	parse_time
	@days_of_week = [:monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday]
	
    @venue = Venue.new(venue_only_params)
	
    if @venue.save(venue_only_params)
		if @venue.update_attributes(venue_params)
			flash[:success] = "Successfully created " + @venue.name
			redirect_to venues_path #takes user to index action in venue controller
		else
			flash[:error] = "Opps... looks like we have a problem with saving features"
			render 'new'
		end	  
    else
	  flash[:error] = "Opps... looks like we have a problem "
      render 'new'
    end
  end 
    
  def edit
#  	@venues = Venue.all
	@venue = Venue.find(params[:id])
#	@days_of_week = [:monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday]
#	@days_of_week = Date::DAYNAMES
	@days_of_week = Date::ABBR_DAYNAMES
	session[:section] = params[:section] || session[:section]  # using session variable to track the section of the venues/edit.html form that the user is editing.  This is needed because section is passed as a parameter and in case there is a validation problem with the form, application needs to remember which section that the user was editing.
  end
  
  def update
	parse_time

    @venue = Venue.find(params[:id])

	if @venue.update_attributes(venue_params)
	  flash[:success] = "Venue updated!"
	  if current_user.account_type == "admin"
#		redirect_to venues_path  # takes user to index action in venue controller

		# redirect_to below takes user to show action in venue controller, accessing venues.rb model 
		# (executing callbacks such as format_phone_number) prior to executing show.js.erb, also 
		# passing params[:updated] = true to the show action.
		redirect_to venue_path(id: @venue.id, updated: true) # takes user to show action in venue controller
		
		# Not using render below. Instead, using redirect_to because it will access venues.rb model first
		# which executes callbacks such as format_phone_number within venues.rb.
		# params[:updated] = true # need to set params[:updated] which will be passed to show.js.erb via the render statement below:
		# render 'show'
	  else
		redirect_to venue_path(current_user.venue_id)
	  end
    else
	  flash.now[:error] = "Oops... look like we have errors."
	  @days_of_week = Date::ABBR_DAYNAMES
	  render 'edit'
#	  render js: "alert(#{@venue_name});"
#	  render js: "togglePane({state: 'open', callback: function(){toggleSlider({state: 'open'});}});"	  
    end
  end
 
  def destroy
	Venue.find(params[:id]).destroy
	if User.update_all({account_type: "user", venue_id: ''}, {venue_id: params[:id]})
		flash[:success] = "Venue deleted"
	end
	redirect_to venues_url
  end

 
  private  #See Listing 7.22: Private functions are used internally by the controller (and don't need to be exposed to external users via the Web)
  # shows how to access attributes from another model using accepts_nested_attributes method - http://stackoverflow.com/questions/17371334/how-is-attr-accessible-used-in-rails-4
  
  	def correct_venue_user
		unless (current_user.venue_id == params[:id].to_i) || (current_user.account_type == 'admin')
			flash[:error] = "Ooops... looks like you aren't authorized to access that venue."
			redirect_to root_url
		end	
    end

    def venue_only_params #See Chapter 7.3.2 for strong parameters.  Params.require ensures that the params hash has a :user attribute, and permits only the name, email, password, and password confirmation attributes (but no others) to be passed to Venue.new in the create method.
      params.require(:venue).permit(:name, :address, :city, :state, :zip_code, :description, :phone, :file_name, :logo, :active, :neighborhood_id, :venue_open_mon, :venue_close_mon, :kitchen_open_mon, :kitchen_close_mon, :venue_open_tue, :venue_close_tue, :kitchen_open_tue,:kitchen_close_tue, :venue_open_wed, :venue_close_wed, :kitchen_open_wed, :kitchen_close_wed, :venue_open_thu, :venue_close_thu, :kitchen_open_thu, :kitchen_close_thu, :venue_open_fri, :venue_close_fri, :kitchen_open_fri, :kitchen_close_fri, :venue_open_sat, :venue_close_sat, :kitchen_open_sat, :kitchen_close_sat, :venue_open_sun, :venue_close_sun, :kitchen_open_sun, :kitchen_close_sun, :website )
    end

    def venue_params #See Chapter 7.3.2 for strong parameters.  Params.require ensures that the params hash has a :user attribute, and permits only the name, email, password, and password confirmation attributes (but no others) to be passed to Venue.new in the create method.
      params.require(:venue).permit(:name, :address, :city, :state, :zip_code, :description, :phone, :file_name, :logo, :active, :neighborhood_id, :venue_open_mon, :venue_close_mon, :kitchen_open_mon, :kitchen_close_mon, :venue_open_tue, :venue_close_tue, :kitchen_open_tue,:kitchen_close_tue, :venue_open_wed, :venue_close_wed, :kitchen_open_wed, :kitchen_close_wed, :venue_open_thu, :venue_close_thu, :kitchen_open_thu, :kitchen_close_thu, :venue_open_fri, :venue_close_fri, :kitchen_open_fri, :kitchen_close_fri, :venue_open_sat, :venue_close_sat, :kitchen_open_sat, :kitchen_close_sat, :venue_open_sun, :venue_close_sun, :kitchen_open_sun, :kitchen_close_sun, :website, :feature_ids => [], videos_attributes: [:id, :venue_id, :video_name, :live, :active, :_destroy])
    end

    def parse_time #Need to parse time from the rails combined time select gem - http://excid3.com/blog/rails-tip-4-rails-time-select-like-google-calendar/
      	days_of_week = [:mon, :tue, :wed, :thu, :fri, :sat, :sun]
		venue_or_kitchen = ["venue", "kitchen"]
		open_or_close = ["open", "close"]
		
		days_of_week.each do |day_of_week|
			venue_or_kitchen.each do |v_or_k|
				open_or_close.each do |o_or_c|
					if !params[:venue]["#{v_or_k}_#{o_or_c}_#{day_of_week}(5i)".to_s].nil?
						params[:venue].parse_time_select! "#{v_or_k}_#{o_or_c}_#{day_of_week}".to_s
					end	
				end
			end	
		end	
    end
	
end

app/views/venues/_form_additional.html.erb
	<!-- Additional Info panel -->
	<%= f.text_area :description, placeholder: "Venue Description" %>
	<% if current_user.account_type == "admin" %>
		<%= f.text_field :file_name, placeholder: "File Name (not required)" %>
		<%= f.form_group :active, label: { text: "Active" } do %>
			<%= f.radio_button :active, 1, label: "True", inline: true, checked: (@venue.active == true) %>
			<%= f.radio_button :active, 0, label: "False", inline: true, checked: (@venue.active == false) %>
		<% end %>
	<% else %>
		<%= hidden_field_tag :active, @venue.active %>
	<% end %>

app/views/venues/_form_contact.html.erb
	<!-- Contact info panel -->
	<%= f.text_field :name, placeholder: "Venue Name" %>
	<%= f.text_field :address, placeholder: "Street" %>
	<%= f.text_field :city, placeholder: "City", hide_label: true %>
	<%= f.select :state, ["IL"], prompt: "Select State", hide_label: true %>
	<%= f.text_field :zip_code, placeholder: "Zip Code", hide_label: true %>
	<% if @venue.neighborhood.nil? %>
		<%= f.select :neighborhood_id, Neighborhood.all.collect{|p| [p.name, p.id]}, {include_blank: false, prompt: "Select Neighborhood"} %>
	<% else %>
		<%= f.select :neighborhood_id, Neighborhood.all.collect{|p| [p.name, p.id]}, {include_blank: false, :selected => @venue.neighborhood.id} %>
	<% end %>
	<%= f.text_field :phone, placeholder: "Phone Number" %>
	<%= f.text_field :website, placeholder: "Website" %>			
				
				
<% if false %>				
						<div class="form-group">
							<%= f.label :address, class: 'col-sm-2 control-label' %>
							<div class="col-sm-9">
								<% if current_user.account_type != "admin" %>
									<%= f.text_field :address, class:"form-control", placeholder:"Street", :readonly => true %>
								<% else %>
									<%= f.text_field :address, class:"form-control", placeholder:"Street" %>
								<% end %>
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-4">
								<% if current_user.account_type != "admin" %>
									<%= f.text_field :city, class:"form-control", placeholder:"City", :readonly => true %>
								<% else %>	
									<%= f.text_field :city, class:"form-control", placeholder:"City" %>
								<% end %>
							</div>
							
							<div class="col-sm-2">
								<% if @venue.state.nil? %>
									<%= f.select :state, ["IL"], {:prompt => "ST"}, { :class => "form-control" } %>
								<% else %>
									<% if current_user.account_type != "admin" %>
										<%= f.text_field :state, class:"form-control", placeholder:"City", :readonly => true %>
									<% else %>	
										<%= f.select :state, ["IL"], {:selected => @venue.state}, { :class => "form-control" } %>	
									<% end %>	
								<% end %>
							</div>

							<div class="col-sm-3">
								<% if current_user.account_type != "admin" %>
									<%= f.text_field :zip_code, class:"form-control", placeholder:"Zip", maxlength:"5", :readonly => true %>
								<% else %>
									<%= f.text_field :zip_code, class:"form-control", placeholder:"Zip", maxlength:"5" %>
								<% end %>
							</div>
						</div>

						<div class="form-group">
							<%= f.label :neighborhood_id, "Neighborhood", class: 'col-sm-2 control-label' %>
							<div class="col-sm-10">
								<% if @venue.neighborhood.nil? %>
									<%= f.select :neighborhood_id, Neighborhood.all.collect{|p| [p.name, p.id]}, { :prompt => "Select Neighborhood" } , { :class => "form-control" }%>
								<% else %>	
									<%= f.select :neighborhood_id, Neighborhood.all.collect{|p| [p.name, p.id]}, {include_blank: false, :selected => @venue.neighborhood.id} , { :class => "form-control" }%>
								<% end %>
							</div>
						</div>
<% end %>						

app/views/venues/_form_features.html.erb
			<!-- Features panel -->
			<div class="form-group">
				<%= hidden_field_tag "venue[feature_ids][]", nil %>
				<div class='col-sm-offset-2 col-sm-9'>
					<% Feature.all.each do |feature| %>
						<div class="checkbox">
							<label>
								<%= check_box_tag "venue[feature_ids][]", feature.id, @venue.feature_ids.include?(feature.id) %>
								<%= feature.name %><br>
							</label>
						</div>
					<% end %>
				</div>
			</div>	

app/views/venues/_form_hours_kitchen.html.erb
			<!-- Kitchen hours -->								
				<% @days_of_week.each do |day_of_week| %>
					<div class="form-group">					
						<%= label_tag day_of_week.to_s.capitalize, nil, class: 'col-xs-2 col-md-offset-0 control-label' %>
						<div class='col-xs-5 col-sm-3 col-md-4 col-lg-3'>
							<%= f.time_select time_field_helper("open", day_of_week, "kitchen"),
								{:combined => true,
								:hide_label => true,
								:label_col => "col-xs-12",
								:ampm => true,
								:include_blank => false,
								:prompt => "Open",
								:minute_interval => 30,
								:time_separator => "",
								:start_hour => 0,
								:start_minute => 00,
								:end_hour => 23,
								:end_minute => 59}, 
								{:class => ""}
							%>
						</div>	
						<div class='col-xs-5 col-sm-3 col-md-4 col-lg-3'>
							<%= f.time_select time_field_helper("close", day_of_week, "kitchen"),
								{:combined => true,
								:hide_label => true,
								:label_col => "col-xs-12",
								:ampm => true,
								:include_blank => false,
								:prompt => "Close",
								:minute_interval => 30,
								:time_separator => "",
								:start_hour => 0,
								:start_minute => 00,
								:end_hour => 23,
								:end_minute => 59},
								{:class => "no-margin"}
							%>
						</div>	
					</div>
				<% end %>

app/views/venues/_form_hours_venue.html.erb
			<!-- Venue hours -->
				<% @days_of_week.each do |day_of_week| %>
					<div class="form-group">
						<%= label_tag day_of_week.to_s.capitalize, nil, class: 'col-xs-2 col-md-offset-2 control-label' %>
						<div class='col-xs-5 col-sm-3 col-md-4 col-lg-3'>
							<%= f.time_select time_field_helper("open", day_of_week), 
								{:combined => true,
								:hide_label => true,
								:label_col => "col-xs-12",
								:ampm => true,
								:include_blank => false,
								:prompt => "Open",
								:minute_interval => 30,
								:time_separator => "",
								:start_hour => 0,
								:start_minute => 00,
								:end_hour => 23,
								:end_minute => 59}, 
								{:class => ""}
							%>
						</div>
						<div class='col-xs-5 col-sm-3 col-md-4 col-lg-3'>
							<%= f.time_select time_field_helper("close", day_of_week),
								{:combined => true,
								:hide_label => true,
								:label_col => "col-xs-12",
								:ampm => true,
								:include_blank => false,
								:prompt => "Close",
								:minute_interval => 30,
								:time_separator => "",
								:start_hour => 0,
								:start_minute => 00,
								:end_hour => 23,
								:end_minute => 59},
								{:class => ""}
							%>
						</div>	
					</div>
				<% end %>
	

app/views/venues/index.html.erb
<div class="container">

	<div class="panel panel-default">
	
		<!-- Default panel contents -->
		<div class="panel-heading">
			<%= link_to "Add Venue", new_venue_path, class:"btn btn-xs btn-primary pull-right" %>
			<h3 class="panel-title format-inline">Venues Index</h3>
		</div>
		
		<div class="table-responsive well">
			<table class="table table-condensed table-hover">
				<thead>
					<tr>
						<th class="visible-lg">ID</th>
						<th>Venue</th>
						<th>Events</th>
						<th>Finished Videos</th>
						<th>Processing Videos</th>
						<th>Failed Videos</th>
						<th>Views</th>
						<th>&nbsp;</th>
					</tr>
				</thead>
				<tbody> 
					<% for venue in @venues %>
						<tr>
							<td class="visible-lg"><%= venue.id %></td>
							<td><%= link_to venue.name, edit_venue_path(venue.id) %></td>							
							<td><%= link_to venue.venue_events.count, venue_events_path(:venue_id => venue.id) %></td>
							<td><%= link_to venue.count_videos("finished"), videos_path(:venue_id => venue.id) %></td>
							<td><%= venue.count_videos("processing") %></td>
							<td><%= venue.count_videos("failed") %></td>
							<td>TBD</td>
							<td><%= link_to "Delete", venue, method: :delete, data: { confirm: "You sure?" } %></td>
						</tr>	
					<% end %>
				</tbody>
			</table>
		</div> <!-- table -->
		
	</div> <!-- panel -->
	
</div> <!-- container -->