config/routes.rb
Altoids::Application.routes.draw do

	root 'sessions#splash'
  
	match '/splash', to: 'sessions#splash', via: 'get'
  	match '/home', to: 'sessions#home', via: 'get'
	match '/events_list', to: 'sessions#events_list', via: 'get'
	match '/tearsheet', :to => 'sessions#tearsheet', via: 'get'
	match '/logout', to: 'sessions#destroy', via: 'get'
	
	post 'zencoder' => 'zencoder#create', :as => 'zencoder' # used to direct the "completed job" notification from zencoder	
	  
	resources :videos
	resources :products
	resources :sessions, only: [:new, :create, :destroy]
	resources :users
	resources :venues
	resources :neighborhoods
	resources :features
	resources :venue_features
	resources :events
	resources :venue_events
	resources :password_resets
	

end

app/views/layouts/_filter_options.html.erb
		<!-- FILTER -->
		<div id="filter_options">
			<div class="section">
				<span>FEATURES</span>
			</div>
			
			<!-- data-toggle="buttons" disables links -->
			<div class="btn-group-vertical">
				<% for feature in Feature.all do %>
					<label class="btn btn-glass">
						<input id="<%= feature.name %>" class="filter" name="features[]" type="checkbox" value="<%= feature.name %>" <%= filter_selection(params[:features], feature.name, "checked") %> />&nbsp;<%= feature.name %>
					</label>
				<% end %>
			</div>
			
			<div class="section">
				<span>NEIGHBORHOOD</span>
			</div>
			

			<!-- data-toggle="buttons" disables links -->
			<div class="btn-group-vertical">
				<% for neighborhood in Neighborhood.all do %>
					<label class="btn btn-glass">
						<input id="<%= neighborhood.name %>" class="filter" name="neighborhoods[]" type="checkbox" value="<%= neighborhood.name %>" <%= filter_selection(params[:neighborhoods], neighborhood.name, "checked") %> />&nbsp;<%= neighborhood.name %>
					</label>
				<% end %>
			</div>
		</div>

			
<% if false %>
			<div class="section">
				<span>FILTERS</span>
			</div>
	
			<div class="content">
<% if false %>			
				<div class="subsection">
					<span>SEARCH</span>
				</div>
		
				<p>
					<%= text_field_tag :search, params[:search] %>
						<%= text_field_tag :search, params[:search], {id:'search'} %>
						<%= submit_tag "Search", :name => nil %>
				</p>
<% end %>
				<div class="subsection">
					FEATURES
				</div>
				
				<!-- data-toggle="buttons" disables links -->
				<div class="btn-group-vertical">
					<% for feature in Feature.all do %>
						<label class="btn btn-glass">
							<input id="<%= feature.name %>" class="filter" name="features[]" type="checkbox" value="<%= feature.name %>" <%= filter_selection(params[:features], feature.name, "checked") %> />&nbsp;<%= feature.name %>
						</label>
					<% end %>
				</div>
		
				<div class="subsection">
					NEIGHBORHOOD
				</div>
				
				<!-- data-toggle="buttons" disables links -->
				<div class="btn-group-vertical">
					<% for neighborhood in Neighborhood.all do %>
						<label class="btn btn-glass">
							<input id="<%= neighborhood.name %>" class="filter" name="neighborhoods[]" type="checkbox" value="<%= neighborhood.name %>" <%= filter_selection(params[:neighborhoods], neighborhood.name, "checked") %> />&nbsp;<%= neighborhood.name %>
						</label>
					<% end %>
<% if false %>
					<label class="btn btn-glass filter_neighborhood">
						<input id="Lincoln Park" name="neighborhood[]" type="checkbox" value="Lincoln Park" <%= filter_selection(params[:neighborhood], "Lincoln Park", "checked") %> /> Lincoln Park
					</label>
					<label class="btn btn-glass filter_neighborhood">
						<input id="Old Town" name="neighborhood[]" type="checkbox" value="Old Town" <%= filter_selection(params[:neighborhood], "Old Town", "checked") %> /> Old Town
					</label>
<% end %>					
				</div>
			</div>
<% end %>

app/views/layouts/_filter_sort_menu.html.erb
	<%= form_tag home_path, :method => 'get', :id => "form_sortFilter" do %>
<% if false %>
		<%= hidden_field_tag :sort_order, params[:sort_order], {id:'sort_order'} %>
		<%= hidden_field_tag :latitude, params[:latitude], {id:'hidden_field_latitude'} %>
		<%= hidden_field_tag :longitude, params[:longitude], {id:'hidden_field_longitude'} %>
<% end %>

		<div class="section">
			SEARCH
		</div>

		<div class="content">
			<%= text_field_tag :search, params[:search], class:"search_field", placeholder: 'Enter venue...' %>
		</div>

		<%= render partial: "layouts/sort_options" %>		
		<%= render partial: "layouts/filter_options" %>	

	<% end %>

app/views/layouts/_footer.erb
		<div class="container">
			<p class="pull-right"><a href="#">Back to top</a></p>
			<p>&copy; 2014 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
		</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<%# Adapted with code from: https://gist.github.com/roberto/3344628 %>

<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_modal.html.erb
<div class="modal fade" id="mainModal" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" id="btn-close" class="close" data-dismiss="modal">
					<span aria-hidden="true">&times;</span>
					<span class="sr-only">Close</span>
				</button>
				<h4 class="modal-title"></h4>
			</div>
			<div class="modal-body">
				<div class="row preloader collapse">
					<div class="col-sm-12">
						<%= image_tag("preloader.GIF", class:"image-center margin-10") %>
					</div>
					<div class="col-sm-12">
						<p class="text-center" >Please wait...<p>
					</div>
				</div>
				<div class="modal-body-content">
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" id="btn-default" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="button" id="btn-primary" class="btn btn-primary"></button>
			</div>
		</div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/_navigation.html.erb
<%# using styling from carousel-theme.css %>

        <div id="navbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="#">Project name</a>
				</div>
				<div class="collapse navbar-collapse">
					<% if current_user && current_user.account_type == "admin" %>									
						<%= render 'layouts/navigation_links' %>
					<% end %>
					<%= render 'layouts/navigation_links_right' %>
				</div>
				
			</div>
        </div>

app/views/layouts/_navigation_links.erb
					<ul class="nav navbar-nav">
						<li class= <%= navbar_active_helper('users') %> ><%= link_to "Users", users_path %></li>
						<li class= <%= navbar_active_helper('venues') %> ><%= link_to "Venues", venues_path %></li>						
						<li class="dropdown <%= navbar_active_helper('other') %> " >
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Other <b class="caret"></b></a>
							<ul class="dropdown-menu">
						
								<!-- Neighborhood dropdowns -->
								<li><%= link_to "Neighborhoods", neighborhoods_path %></li>
								
								<!-- Features dropdown -->			
								<li><%= link_to "Features", features_path %></li>
								
								<!-- Events dropdown -->			
								<li><%= link_to "Events", events_path %></li>
								
							</ul>
						</li>
					</ul>	

app/views/layouts/_navigation_links_right.erb
<%# Non-administrator management menu - located on right side of navigation bar %>

<ul class="nav navbar-nav navbar-right">
	<% if current_user %>		
		<li class= <%= navbar_active_helper('sessions') %> ><%= link_to "Home", home_path %></li>
		
		<!-- Venue Management dropdown menu -->
		<% if current_user.account_type == "venue" %>
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.venue.name %> <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li><%= link_to "Venue Profile", edit_venue_path(current_user.venue_id) %></li>
					<li><%= link_to "Events", venue_events_path(:venue_id => current_user.venue_id) %></li>
					<li><%= link_to "Videos", videos_path(:venue_id => current_user.venue_id) %></li>
				</ul>
			</li>
		<% end %>

		<!-- User dropdown menu -->
		<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Hi,&nbsp;<%= current_user.first_name %>! <b class="caret"></b></a>
			<ul class="dropdown-menu">
				<li><%= link_to "My Profile", edit_user_path(current_user.id), id:"button_user_edit", data: { modal_title: possessive(current_user.first_name) + " Profile" } %></li>
				<li><%= link_to "Log out", session_path(current_user.id), method: :delete %></li>
			</ul>
		</li>	
	<% else %>
		<!-- Signing up for new account modal window -->
		<li><%= link_to "Sign Up", '#', :"data-toggle" => "modal", :"data-target" => "#myModal" %></li>

		<!-- User log in - dropdown form -->
		<li class="dropdown">
			<a href="#!" class="dropdown-toggle" data-toggle="dropdown">Log In<b class="caret"></b></a>
			<ul id="log_in_form" class="dropdown-menu">
				<%= bootstrap_form_for(:session, url: sessions_path, layout: :horizontal, label_col: "col-sm-0", control_col: "col-sm-12") do |f| %>
					<%= render 'sessions/log_in_fields', f: f %>
					<div class="form_group">
						<div class="col-xs-12">
							<%= f.submit 'Sign In', class: 'btn btn-success btn-sm' %>
						</div>
					</div>
				<% end %>
			</ul>
		</li>
	<% end %>
</ul>

app/views/layouts/_sort_options.html.erb
<!-- Radio buttons - used to pass parameter values by form if not using ajax. -->
		<div class="section">
			<span>SORT BY</span>
		</div>

		<div class="content">

			<div id="sort_options" class="btn-group">
				
				<!-- Default selection: Events -->

				<%= button_tag(type: "button", class:"btn btn-glass sort #{filter_selection(params[:sort_order], 'event', 'active', default: true)}", id:"event") do %>
					<span class="glyphicon glyphicon-ok"></span><br>
					<%= radio_button_tag "sort_order", "event", filter_selection(params[:sort_order], "event", true, default: true), class: "hidden" %>
					<span class="title text-center">Events</span>
				<% end %>

				<%= button_tag(type: "button", class:"btn btn-glass sort #{filter_selection(params[:sort_order], 'distance', 'active')}", id:"distance") do %>
					<span class="glyphicon glyphicon-map-marker"></span><br>
					<%= radio_button_tag "sort_order", "distance", filter_selection(params[:sort_order], "distance", true), class: "hidden" %>					
					<span class="title text-center">Distance<span>
				<% end %>

				<%= button_tag(type: "button", class:"btn btn-glass sort #{filter_selection(params[:sort_order], 'name_asc', 'active')}", id:"name_asc") do %>
					<span class="glyphicon glyphicon-arrow-down"></span><br>
					<%= radio_button_tag "sort_order", "name_asc", filter_selection(params[:sort_order], "name_asc", true), class: "hidden" %>
					<span class="title text-center">A-Z</span>
				<% end %>
								
				<!-- Button Display: Z-A, Future Sort: Z-A -->
				<%= button_tag(type: "button", class:"btn btn-glass sort #{filter_selection(params[:sort_order], 'name_desc', 'active')}", id:"name_desc") do %>
					<span class="glyphicon glyphicon-arrow-up"></span><br>
					<%= radio_button_tag "sort_order", "name_desc", filter_selection(params[:sort_order], "name_desc", true), class: "hidden" %>					
					<span class="title text-center">Z-A</span>
				<% end %>
				
				<%= button_tag(type: "button", class:"btn btn-glass sort #{filter_selection(params[:sort_order], 'neighborhood', 'active')}", id:"neighborhood") do %>
					<span class="glyphicon glyphicon-pushpin"></span><br>
					<%= radio_button_tag "sort_order", "neighborhood", filter_selection(params[:sort_order], "neighborhood", true), class: "hidden" %>
					<span class="title text-center">Hood</span>
				<% end %>
				
			</div>
		</div>
		
		
<% if false %>
<!-- Radio buttons - used to pass parameter values by form if not using ajax. -->
		<div class="section">
			<span>SORT BY</span>
		</div>

		<div class="content">

			<!-- data-toggle="buttons" disables links -->
			<div id="sort_options" class="btn-group">
				
				<!-- Default selection: Events -->
				<!-- params.merge - adds parameters (i.e. hidden parameters such as :search, url parameters from a previous request, etc.) to the url (besides the url parameters, :sort and :page) -->
				<%= link_to home_path(params.merge(:sort_order => 'event', :page => nil)), class:"btn btn-glass sort #{filter_selection(params[:sort_order], 'event', 'active', default: true)}", id:'event', :data => { :sort => 'event' } do %>
					<span class="glyphicon glyphicon-ok"></span><br>
					<%= radio_button_tag 'sort_order', 'event', filter_selection(params[:sort_order], 'event', true, default: true), class: "hidden" %>
					<span class="title text-center">Events</span>
				<% end %>

				<%= link_to home_path(params.merge(:sort_order => 'distance', :page => nil)), class:"btn btn-glass sort #{filter_selection(params[:sort_order], 'distance', 'active')}", id:'distance', :data => { :sort => 'distance' } do %>
					<span class="glyphicon glyphicon-map-marker"></span><br>
					<%= radio_button_tag 'sort_order', 'distance', filter_selection(params[:sort_order], 'distance', true), class: "hidden" %>
					<span class="title text-center">Distance<span>
				<% end %>

				<%= link_to home_path(params.merge(:sort_order => 'name_asc', :page => nil)), class:"btn btn-glass sort #{filter_selection(params[:sort_order], 'name_asc', 'active')}", id:'name_asc', :data => { :sort => 'name_asc' } do %>
					<span class="glyphicon glyphicon-arrow-down"></span><br>
					<%= radio_button_tag 'sort_order', 'name_asc', filter_selection(params[:sort_order], 'name_asc', true), class: "hidden" %>
					<span class="title text-center">A-Z</span>
				<% end %>
								
				<!-- Button Display: Z-A, Future Sort: Z-A -->	
				<%= link_to home_path(params.merge(:sort_order => 'name_desc', :page => nil)), class:"btn btn-glass sort #{filter_selection(params[:sort_order], 'name_desc', 'active')}", id:'name_desc', :data => { :sort => 'name_desc' } do %>
					<span class="glyphicon glyphicon-arrow-up"></span><br>
					<%= radio_button_tag 'sort_order', 'name_desc', filter_selection(params[:sort_order], 'name_desc', true), class: "hidden" %>
					<span class="title text-center">Z-A</span>
				<% end %>
				
				<%= link_to home_path(params.merge(:sort_order => 'neighborhood', :page => nil)), class:"btn btn-glass sort #{filter_selection(params[:sort_order], 'neighborhood', 'active')}", id:'neighborhood', :data => { :sort => 'neighborhood' } do %>
					<span class="glyphicon glyphicon-pushpin"></span><br>
					<%= radio_button_tag 'sort_order', 'neighborhood', filter_selection(params[:sort_order], 'neighborhood', true), class: "hidden" %>
					<span class="title text-center">Hood</span>
				<% end %>
				
			</div>
		</div>
<% end %>		

app/views/layouts/application.html.erb
<!-- Desktop version -->

<!DOCTYPE html>
<html>
<head>
	<title>BarFly</title>

	<%# Removes auto-styling for telephone numbers in application:  http://stackoverflow.com/questions/3736807/remove-styling-of-telephone-numbers %> 
	<meta name="format-detection" content="telephone=no">

	<!-- for more info about stylesheet_link_tag and asset pipeline: https://www.reinteractive.net/posts/116-12-tips-for-the-rails-asset-pipeline -->
	<!-- includes desktop-manifest.css -->
	<%= stylesheet_link_tag "desktop-manifest", media: "all", "data-turbolinks-track" => true %>
	
	<!-- includes application.js (manifest file) -->
	<%= javascript_include_tag "application.js", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<header>
		<%= render 'layouts/navigation' %>
	</header>
	
	<div class="container">
		<%= render 'layouts/messages', flash: flash %>
	</div>
	
	<div id="main-content">

		<!-- Modal -->
		<%= render 'layouts/modal' %>
		
		<%= yield %>
	</div>	
	
	<footer>
		<%= render 'layouts/footer' %>
	</footer>

	<%= debug(params) if Rails.env.development? %>
	
</body>
</html>